<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 15px; height: 80px">

# Project 5

## Help Yelp

---

In this project you will be investigating a small version of the [Yelp challenge dataset](https://www.yelp.com/dataset_challenge). You'll practice using classification algorithms, cross-validation, gridsearching â€“ all that good stuff.

---

### The data

There are 5 individual .csv files that have the information, zipped into .7z format like with the SF data last project. The dataset is located in your datasets folder:

    DSI-SF-2/datasets/yelp_arizona_data.7z

The columns in each are:

    businesses_small_parsed.csv
        business_id: unique business identifier
        name: name of the business
        review_count: number of reviews per business
        city: city business resides in
        stars: average rating
        categories: categories the business falls into (can be one or multiple)
        latitude
        longitude
        neighborhoods: neighborhoods business belongs to
        variable: "property" of the business (a tag)
        value: True/False for the property
        
    reviews_small_nlp_parsed.csv
        user_id: unique user identifier
        review_id: unique review identifier
        votes.cool: how many thought the review was "cool"
        business_id: unique business id the review is for
        votes.funny: how many thought the review was funny
        stars: rating given
        date: date of review
        votes.useful: how many thought the review was useful
        ... 100 columns of counts of most common 2 word phrases that appear in reviews in this review
        
    users_small_parsed.csv
        yelping_since: signup date
        compliments.plain: # of compliments "plain"
        review_count: # of reviews:
        compliments.cute: total # of compliments "cute"
        compliments.writer: # of compliments "writer"
        compliments.note: # of compliments "note" (not sure what this is)
        compliments.hot: # of compliments "hot" (?)
        compliments.cool: # of compliments "cool"
        compliments.profile: # of compliments "profile"
        average_stars: average rating
        compliments.more: # of compliments "more"
        elite: years considered "elite"
        name: user's name
        user_id: unique user id
        votes.cool: # of votes "cool"
        compliments.list: # of compliments "list"
        votes.funny: # of compliments "funny"
        compliments.photos: # of compliments "photos"
        compliments.funny: # of compliments "funny"
        votes.useful: # of votes "useful"
       
    checkins_small_parsed.csv
        business_id: unique business identifier
        variable: day-time identifier of checkins (0-0 is Sunday 0:00 - 1:00am,  for example)
        value: # of checkins at that time
    
    tips_small_nlp_parsed.csv
        user_id: unique user identifier
        business_id: unique business identifier
        likes: likes that the tip has
        date: date of tip
        ... 100 columns of counts of most common 2 word phrases that appear in tips in this tip

The reviews and tips datasets in particular have parsed "NLP" columns with counts of 2-word phrases in that review or tip (a "tip", it seems, is some kind of smaller review).

The user dataset has a lot of columns of counts of different compliments and votes. I'm not sure whether the compliments or votes are _by_ the user or _for_ the user.

---

If you look at the website, or the full data, you'll see I have removed pieces of the data and cut it down quite a bit. This is to simplify it for this project. Specifically, business are limited to be in these cities:

    Phoenix
    Surprise
    Las Vegas
    Waterloo

Apparently there is a city called "Surprise" in Arizona. 

Businesses are also restricted to at least be in one of the following categories, because I thought the mix of them was funny:

    Airports
    Breakfast & Brunch
    Bubble Tea
    Burgers
    Bars
    Bakeries
    Breweries
    Cafes
    Candy Stores
    Comedy Clubs
    Courthouses
    Dance Clubs
    Fast Food
    Museums
    Tattoo
    Vape Shops
    Yoga
    
---

### Project requirements

**You will be performing 4 different sections of analysis, like in the last project.**

Remember that classification targets are categorical and regression targets are continuous variables.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [2]:
businesses = pd.read_csv('/Users/alex/Desktop/DSI-SF-2-akodate/datasets/yelp_arizona_data/businesses_small_parsed.csv')
reviews = pd.read_csv('/Users/alex/Desktop/DSI-SF-2-akodate/datasets/yelp_arizona_data/reviews_small_nlp_parsed.csv')
users = pd.read_csv('/Users/alex/Desktop/DSI-SF-2-akodate/datasets/yelp_arizona_data/users_small_parsed.csv')
checkins = pd.read_csv('/Users/alex/Desktop/DSI-SF-2-akodate/datasets/yelp_arizona_data/checkins_small_parsed.csv')
tips = pd.read_csv('/Users/alex/Desktop/DSI-SF-2-akodate/datasets/yelp_arizona_data/tips_small_nlp_parsed.csv')

print "businesses:", businesses.shape
print "reviews:", reviews.shape
print "users:", users.shape
print "checkins:", checkins.shape
print "tips:", tips.shape

businesses: (152832, 11)
reviews: (322398, 108)
users: (144206, 21)
checkins: (214299, 3)
tips: (101991, 104)

In [136]:
print businesses['city'].value_counts()
businesses.head()

Las Vegas    93818
Phoenix      53279
Surprise      2974
Waterloo      2761
Name: city, dtype: int64

,business_id,name,review_count,city,stars,categories,variable,value
0,EmzaQR5hQlF0WIl24NxAZA,Sky Lounge,25,Phoenix,2.5,"['American (New)', 'Nightlife', 'Dance Clubs',...",attributes.Ambience.divey,False
1,SiwN7f0N4bs4ZtPc4yPgiA,Palazzo,19,Phoenix,3.0,"['Bars', 'Nightlife', 'Dance Clubs']",attributes.Ambience.divey,False
2,e5kc0CQ4R-PCCDgb274gSg,Canyon Cafe,238,Phoenix,3.5,"['Cafes', 'Mexican', 'Tex-Mex', 'Restaurants']",attributes.Ambience.divey,False
3,neGAQFkBNI8-rpPBLBzNkw,Taco Bell,10,Phoenix,4.0,"['Fast Food', 'Mexican', 'Tex-Mex', 'Restauran...",attributes.Ambience.divey,False
4,45puCRQ6Vh_IIAy7kkfFDQ,Majerle's Sports Grill,205,Phoenix,3.5,"['Bars', 'Restaurants', 'American (Traditional...",attributes.Ambience.divey,False

In [4]:
print [x for x in reviews.columns]

['user_id', 'review_id', 'votes.cool', 'business_id', 'votes.funny', 'stars', 'date', 'votes.useful', '10 minutes', '15 minutes', '20 minutes', '30 minutes', 'bar food', 'beer selection', 'best ve', 'bloody mary', 'bottle service', 'chicken waffles', 'customer service', 'dance floor', 'decided try', 'definitely come', 'definitely recommend', 'didn want', 'don know', 'don like', 'don think', 'don want', 'eggs benedict', 'fast food', 'feel like', 'felt like', 'fish chips', 'food amazing', 'food came', 'food delicious', 'food good', 'food great', 'food just', 'food service', 'french fries', 'french toast', 'friday night', 'fried chicken', 'friendly staff', 'good food', 'good place', 'good service', 'good thing', 'good time', 'great atmosphere', 'great experience', 'great food', 'great place', 'great service', 'great time', 'happy hour', 'hash browns', 'highly recommend', 'hip hop', 'ice cream', 'just like', 'just ok', 'just right', 'las vegas', 'late night', 'like place', 'little bit', 'long time', 'looked like', 'looks like', 'love place', 'mac cheese', 'make sure', 'mashed potatoes', 'medium rare', 'minutes later', 'new york', 'onion rings', 'place good', 'place great', 'place just', 'potato fries', 'pretty good', 'quality food', 'really enjoyed', 'really good', 'really like', 'really nice', 'recommend place', 'red velvet', 'right away', 'saturday night', 'second time', 'service excellent', 'service food', 'service friendly', 'service good', 'service great', 'staff friendly', 'super friendly', 'sweet potato', 'tasted like', 'time vegas', 'try place', 've seen', 've tried', 'wait staff']

In [5]:
users.head()

,yelping_since,compliments.plain,review_count,compliments.cute,compliments.writer,fans,compliments.note,compliments.hot,compliments.cool,compliments.profile,...,compliments.more,elite,name,user_id,votes.cool,compliments.list,votes.funny,compliments.photos,compliments.funny,votes.useful
0,2004-10,959.0,1274,206.0,327.0,1179,611.0,1094.0,1642.0,116.0,...,134.0,"[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...",Jeremy,rpOyqD_893cqmDAtJLbdog,11093,38.0,7681,330.0,580.0,14199
1,2004-10,89.0,442,23.0,24.0,100,83.0,101.0,145.0,9.0,...,19.0,"[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...",Michael,4U9kSBLuBDU391x6bxU-YA,732,4.0,908,24.0,120.0,1483
2,2004-10,2.0,66,2.0,2.0,4,1.0,1.0,1.0,NaN,...,1.0,[2005],Katherine,SIBCL7HBkrP4llolm4SC2A,13,NaN,11,NaN,NaN,34
3,2004-10,5.0,101,1.0,3.0,7,3.0,5.0,4.0,1.0,...,2.0,[],Nader,UTS9XcT14H2ZscRIf0MYHQ,49,NaN,53,1.0,8.0,243
4,2004-10,104.0,983,82.0,17.0,78,85.0,265.0,212.0,9.0,...,16.0,"[2005, 2006, 2007, 2008, 2010, 2011, 2012]",Helen,ZWOj6LmzwGvMDh-A85EOtA,1928,3.0,1109,57.0,70.0,2404

In [6]:
checkins.head()

              business_id          variable  value
0  SG_gEmEXL4ID6RAEinC5Bg  checkin_info.9-0    1.0
1  45puCRQ6Vh_IIAy7kkfFDQ  checkin_info.9-0    1.0
2  P7wKlbSRsoRrfH3DFOY08A  checkin_info.9-0    1.0
3  qsWxbgQwuomXvMseg23DGg  checkin_info.9-0    1.0
4  VCQ3VvnVRhibTT8J61xWkw  checkin_info.9-0    1.0

In [7]:
print [x for x in tips.columns]

['user_id', 'business_id', 'likes', 'date', '24 hours', 'amazing food', 'animal style', 'awesome food', 'awesome place', 'awesome service', 'beef hash', 'beer selection', 'best breakfast', 'best burger', 'best burgers', 'best place', 'bloody mary', 'bottle service', 'carne asada', 'cheese fries', 'chicken waffles', 'come early', 'cool place', 'corned beef', 'customer service', 'delicious food', 'don come', 'don forget', 'eggs benedict', 'excellent food', 'excellent service', 'fast food', 'fast service', 'favorite place', 'feel like', 'fish chips', 'food amazing', 'food awesome', 'food drinks', 'food good', 'food great', 'food service', 'free wifi', 'french toast', 'fried chicken', 'friendly service', 'friendly staff', 'gluten free', 'good food', 'good place', 'good service', 'great atmosphere', 'great beer', 'great breakfast', 'great burgers', 'great customer', 'great drinks', 'great food', 'great happy', 'great place', 'great prices', 'great service', 'great spot', 'great staff', 'grilled cheese', 'guest list', 'happy birthday', 'happy hour', 'highly recommend', 'ice cream', 'las vegas', 'late night', 'live music', 'long wait', 'love food', 'love love', 'love place', 'mac cheese', 'make sure', 'new favorite', 'nice place', 'nom nom', 'onion rings', 'open 24', 'place awesome', 'place eat', 'place good', 'place great', 'potato fries', 'pretty good', 'prime rib', 'really good', 'red velvet', 'service food', 'service good', 'service great', 'slow service', 'staff friendly', 'staff great', 'steak eggs', 'super friendly', 'sweet potato', 'velvet pancakes', 'worth wait']

In [8]:
businesses = businesses.drop(['latitude', 'longitude', 'neighborhoods'], axis=1)

In [109]:
businesses.head()

,business_id,name,review_count,city,stars,categories,variable,value
0,EmzaQR5hQlF0WIl24NxAZA,Sky Lounge,25,Phoenix,2.5,"['American (New)', 'Nightlife', 'Dance Clubs',...",attributes.Ambience.divey,False
1,SiwN7f0N4bs4ZtPc4yPgiA,Palazzo,19,Phoenix,3.0,"['Bars', 'Nightlife', 'Dance Clubs']",attributes.Ambience.divey,False
2,e5kc0CQ4R-PCCDgb274gSg,Canyon Cafe,238,Phoenix,3.5,"['Cafes', 'Mexican', 'Tex-Mex', 'Restaurants']",attributes.Ambience.divey,False
3,neGAQFkBNI8-rpPBLBzNkw,Taco Bell,10,Phoenix,4.0,"['Fast Food', 'Mexican', 'Tex-Mex', 'Restauran...",attributes.Ambience.divey,False
4,45puCRQ6Vh_IIAy7kkfFDQ,Majerle's Sports Grill,205,Phoenix,3.5,"['Bars', 'Restaurants', 'American (Traditional...",attributes.Ambience.divey,False

In [137]:
# businesses.groupby('business_id', as_index=False).aggregate(lambda x: list(set(x)))

In [130]:
df_wide = pd.pivot_table(businesses, 
                        columns=['variable'],
                        values='value',
                        index=['business_id'],
                        aggfunc=lambda x: [][0] if len(x.values) > 1 else x.values[0],
                        fill_value=np.nan)

In [131]:
print df_wide.shape
df_wide.head()

(4132, 78)

variable,attributes.Accepts Credit Cards,attributes.Accepts Insurance,attributes.Ages Allowed,attributes.Alcohol,attributes.Ambience.casual,attributes.Ambience.classy,attributes.Ambience.divey,attributes.Ambience.hipster,attributes.Ambience.intimate,attributes.Ambience.romantic,...,hours.Saturday.open,hours.Sunday.close,hours.Sunday.open,hours.Thursday.close,hours.Thursday.open,hours.Tuesday.close,hours.Tuesday.open,hours.Wednesday.close,hours.Wednesday.open,open
business_id,,,,,,,,,,,,,,,,,,,,,
--jFTZmywe7StuZ2hEjxyA,True,NaN,NaN,none,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
-0HGqwlfw3I8nkJyMHxAsQ,True,NaN,NaN,none,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
-0VK5Z1BfUHUYq4PoBYNLw,True,NaN,NaN,full_bar,True,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
-0bUDim5OGuv8R0Qqq6J4A,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
-1bOb2izeJBZjHC7NWxiPA,True,NaN,NaN,none,True,False,False,False,False,False,...,06:30,14:30,06:30,14:30,06:30,14:30,06:30,14:30,06:30,True

In [140]:
businesses_wide = businesses.drop(['variable', 'value'], axis=1)

In [141]:
def widen_categories(row):
    

businesses_wide.apply(widen_categories)

,business_id,name,review_count,city,stars,categories
0,EmzaQR5hQlF0WIl24NxAZA,Sky Lounge,25,Phoenix,2.5,"['American (New)', 'Nightlife', 'Dance Clubs',..."
1,SiwN7f0N4bs4ZtPc4yPgiA,Palazzo,19,Phoenix,3.0,"['Bars', 'Nightlife', 'Dance Clubs']"
2,e5kc0CQ4R-PCCDgb274gSg,Canyon Cafe,238,Phoenix,3.5,"['Cafes', 'Mexican', 'Tex-Mex', 'Restaurants']"
3,neGAQFkBNI8-rpPBLBzNkw,Taco Bell,10,Phoenix,4.0,"['Fast Food', 'Mexican', 'Tex-Mex', 'Restauran..."
4,45puCRQ6Vh_IIAy7kkfFDQ,Majerle's Sports Grill,205,Phoenix,3.5,"['Bars', 'Restaurants', 'American (Traditional..."

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 1. Constructing a "profile" for Las Vegas

---

Yelp is interested in building out what they are calling "profiles" for cities. They want you to start with just Las Vegas to see what a prototype of this would look like. Essentially, they want to know what makes Las Vegas distinct from the other four.

Use the data you have to predict Las Vegas from the other variables you have. You should not be predicting the city from any kind of location data or other data perfectly associated with that city (or another city).

You may use any classification algorithm you deem appropriate, or even multiple models. You should:

1. Build at least one model predicting Las Vegas vs. the other cities.
- Validate your model(s).
- Interpret and visualize, in some way, the results.
- Write up a "profile" for Las Vegas. This should be a writeup converting your findings from the model(s) into a human-readable description of the city.

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 2. Different categories of ratings

---

Yelp is finally ready to admit that their rating system sucks. No one cares about the ratings, they just use the site to find out what's nearby. The ratings are simply too unreliable for people. 

Yelp hypothesizes that this is, in fact, because different people tend to give their ratings based on different things. They believe that perhaps some people always base their ratings on quality of food, others on service, and perhaps other categories as well. 

1. Do some users tend to talk about service more than others in reviews/tips? Divide up the tips/reviews into more "service-focused" ones and those less concerned with service.
2. Create two new ratings for businesses: ratings from just the service-focused reviews and ratings from the non-service reviews.
3. Construct a regression model for each of the two ratings. They should use the same predictor variables (of your choice). 
4. Validate the performance of the models.
5. Do the models coefficients differ at all? What does this tell you about the hypothesis that there are in fact two different kinds of ratings?

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 3. Identifying "elite" users

---

Yelp, though having their own formula for determining whether a user is elite or not, is interested in delving deeper into what differentiates an elite user from a normal user at a broader level.

Use a classification model to predict whether a user is elite or not. Note that users can be elite in some years and not in others.

1. What things predict well whether a user is elite or not?
- Validate the model.
- If you were to remove the "counts" metrics for users (reviews, votes, compliments), what distinguishes an elite user, if anything? Validate the model and compare it to the one with the count variables.
- Think of a way to visually represent your results in a compelling way.
- Give a brief write-up of your findings.

<img src="http://imgur.com/GCAf1UX.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 4. Find something interesting on your own

---

You want to impress your superiors at Yelp by doing some investigation into the data on your own. You want to do classification, but you're not sure on what.

1. Create a hypothesis or hypotheses about the data based on whatever you are interested in, as long as it is predicting a category of some kind (classification).
2. Explore the data visually (ideally related to this hypothesis).
3. Build one or more classification models to predict your target variable. **Your modeling should include gridsearching to find optimal model parameters.**
4. Evaluate the performance of your model. Explain why your model may have chosen those specific parameters during the gridsearch process.
5. Write up what the model tells you. Does it validate or invalidate your hypothesis? Write this up as if for a non-technical audience.

<img src="http://imgur.com/GCAf1UX.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 5. ROC and Precision-recall

---

Some categories have fewer overall businesses than others. Choose two categories of businesses to predict, one that makes your proportion of target classes as even as possible, and another that has very few businesses and thus makes the target varible imbalanced.

1. Create two classification models predicting these categories. Optimize the models and choose variables as you see fit.
- Make confusion matrices for your models. Describe the confusion matrices and explain what they tell you about your models' performance.
- Make ROC curves for both models. What do the ROC curves describe and what do they tell you about your model?
- Make Precision-Recall curves for the models. What do they describe? How do they compare to the ROC curves?
- Explain when Precision-Recall may be preferable to ROC. Is that the case in either of your models?